version: "3.8"

services:
     ben_app:
          build:
               context: .
               dockerfile: docker/php/Dockerfile
          container_name: ben_app
          working_dir: /var/www
          volumes:
               - ./src:/var/www
               - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
          environment:
               - DB_HOST=ben_postgres
               - DB_PORT=${POSTGRES_PORT}
               - DB_DATABASE=${POSTGRES_DB}
               - DB_USERNAME=${POSTGRES_USER}
               - DB_PASSWORD=${POSTGRES_PASSWORD}
               - REDIS_HOST=ben_redis
               - REDIS_PORT=${REDIS_PORT}
          expose:
               - ${PHP_PORT}
          depends_on:
               - ben_postgres
               - ben_redis
          networks:
               - ben_network

     ben_nginx:
          image: nginx:latest
          container_name: ben_nginx
          ports:
               - "${APP_PORT}:${NGINX_PORT}"
          volumes:
               - ./src:/var/www
               - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
          depends_on:
               - ben_app
          networks:
               - ben_network

     ben_postgres:
          image: postgres:latest
          container_name: ben_postgres
          environment:
               POSTGRES_DB: ${POSTGRES_DB}
               POSTGRES_USER: ${POSTGRES_USER}
               POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          ports:
               - "${POSTGRES_PORT}:5432"
          volumes:
               - pgdata:/var/lib/postgresql/data
          networks:
               - ben_network

     ben_pgadmin:
          image: dpage/pgadmin4
          container_name: ben_pgadmin
          environment:
               PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
               PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_EMAIL}
          ports:
               - "${PGADMIN_PORT}:80"
          depends_on:
               - ben_postgres
          networks:
               - ben_network

     ben_redis:
          image: redis:latest
          container_name: ben_redis
          ports:
               - "${REDIS_PORT}:6379"
          networks:
               - ben_network

networks:
     ben_network:
          driver: bridge

volumes:
     pgdata:
